#!/bin/bash

case "$1" in
	on)
		echo "autoindex on;" > /etc/nginx/autoindex.conf
		service nginx restart
		;;
	off)
		echo "autoindex off;" > /etc/nginx/autoindex.conf
		service nginx restart
		;;
	*)
	echo $"Usage: $0 {on|off}"
	exit 1
esac
